// <auto-generated />
using HouseRent.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HouseRent.Migrations
{
    [DbContext(typeof(HouseRentContext))]
    [Migration("20180528113555_Advertise")]
    partial class Advertise
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HouseRent.Models.Advertise", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Category");

                    b.Property<string>("FlatDetails");

                    b.Property<decimal>("FlatSize");

                    b.Property<string>("Heading");

                    b.Property<decimal>("OtherBill");

                    b.Property<string>("Phone");

                    b.Property<DateTime>("PostTime");

                    b.Property<decimal>("Rent");

                    b.Property<string>("UserMail");

                    b.Property<decimal>("UtilitiesBill");

                    b.HasKey("ID");

                    b.ToTable("Advertise");
                });

            modelBuilder.Entity("HouseRent.Models.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AdvertiseID");

                    b.Property<bool>("Anonymous");

                    b.Property<string>("CommentText");

                    b.Property<DateTime>("CommentTime");

                    b.Property<string>("Commenter");

                    b.HasKey("ID");

                    b.HasIndex("AdvertiseID");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("HouseRent.Models.Image", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AdvertiseID");

                    b.Property<byte[]>("FlatImage");

                    b.HasKey("ID");

                    b.HasIndex("AdvertiseID");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("HouseRent.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<byte[]>("Avatar");

                    b.Property<string>("Contact");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Role");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("HouseRent.Models.Comment", b =>
                {
                    b.HasOne("HouseRent.Models.Advertise")
                        .WithMany("Comments")
                        .HasForeignKey("AdvertiseID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HouseRent.Models.Image", b =>
                {
                    b.HasOne("HouseRent.Models.Advertise")
                        .WithMany("Images")
                        .HasForeignKey("AdvertiseID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
